### ISSUE TITLE
Janus ID should be u64 ?

### ISSUE THREAD

**Issue by fcx-mrogez** [Ghamza-Jd/jarust#158]
In commit https://github.com/Ghamza-Jd/jarust/commit/7e97c4a3ecc41cf06dbffec120f452fa3ebd0596 janus ID were downgraded to u32 but to me this looks wrong.

For instance, audio room ID are u64 https://github.com/meetecho/janus-gateway/blob/master/src/plugins/janus_audiobridge.c#L1477. But it looks like most (all ?) plugins tracks ID using u64.
The json type used for ID is json_int_t (https://jansson.readthedocs.io/en/latest/apiref.html#c.json_int_t) which is "long long" so still 64bit.

What did justify this downgrade to u32 ? In the commit it says that e2e tests revealed that, but in my experience (limited to the streaming plugin), u64 works just fine.
Thanks

**Comment by Ghamza-Jd** [comment]
Hey - Thanks for raising this!

Actually you're right it should be u64, but I think I found what's wrong.

`json_int_t` is a `long long` but not `unsigned long long`, so anything above `u64::MAX / 2` is considered invalid and getting this

```
{
   "janus": "error",
   "error": {
      "code": 454,
      "reason": "Invalid Janus API request - <string>(1,68): too big integer near '9223372036854775817'"
   }
}
```

**Comment by Ghamza-Jd** [comment]
Janus is expecting a positive JSON_INTEGER
https://github.com/meetecho/janus-gateway/blob/230f6e7196dcae6491dee3ae76a3136821b03e21/src/plugins/janus_audiobridge.c#L1278

**Comment by fcx-mrogez** [comment]
Indeed, it expects positive i64. I was a bit concerned that you encountered some bugs around the fact that json integers are limited to 2^53 precision (https://stackoverflow.com/a/16810116), but this limitation is more related when interfacing with javascript from what I understand.

**Comment by Ghamza-Jd** [comment]
I've created a `U63` type, https://github.com/Ghamza-Jd/jarust/blob/fix/minor-fixes/jarust_plugins/src/common.rs

Let me know what do you think

**Comment by fcx-mrogez** [comment]
Looks good to me. Thanks for looking into that quickly ;)
